version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $DOCKER_DAEMON:/tmp/docker.sock:ro
      - $CERTS:/etc/nginx/certs

networks:
  default:
    external:
      name: nginx-proxy