version: '3'

services:
  nginx-proxy:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/vhost:/etc/nginx/vhost.d
      - $DOCKER_DAEMON:/tmp/docker.sock:ro
      - $CERTS:/etc/nginx/certs
      - ./dhparam.pem:/etc/nginx/dhparam/dhparam.pem

networks:
  default:
    external:
      name: $DOCKER_NETWORK